"""add_user_settings_and_weekly_digests

Revision ID: 384d18c6e747
Revises: 36b9d7be4e21
Create Date: 2026-03-14 14:38:45.139877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '384d18c6e747'
down_revision: Union[str, None] = '36b9d7be4e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recommendations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('volume_assessment', sa.Text(), nullable=True),
    sa.Column('training_load_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_user_week')
    )
    op.create_index(op.f('ix_weekly_digests_user_id'), 'weekly_digests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('auto_post_comments', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('preferred_sports', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('users', sa.Column('weekly_volume_target_km', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('race_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('race_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('race_distance_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'race_distance_km')
    op.drop_column('users', 'race_date')
    op.drop_column('users', 'race_name')
    op.drop_column('users', 'weekly_volume_target_km')
    op.drop_column('users', 'preferred_sports')
    op.drop_column('users', 'auto_post_comments')
    op.drop_index(op.f('ix_weekly_digests_user_id'), table_name='weekly_digests')
    op.drop_table('weekly_digests')
    # ### end Alembic commands ###
